### ISSUE TITLE
Support for printfriendly

### ISSUE THREAD

**Issue by rahul286** [rtCamp/rtsocial#30]
http://www.printfriendly.com/

Might solve #7 and #8 in one go!

There is a wordpress plugin also avaialble for this - http://wordpress.org/plugins/printfriendly/

**Comment by devanshijoshi9** [comment]
@ank1traj 
I install the print-friendly plugin and check with the rtsocial plugin. I found no compatibility issue and this plugin is working fine with rtsocial plugin. Still, it requires QA testing and confirmation.
CC: @pooja-muchandikar

**Comment by pavanpatil1** [comment]
```
Environment:
WordPress: v5.9.1
rtSocial: develop branch
```

Tested the print-friendly plugin with rtsocial. The plugin is working fine with rtSocial.

**Comment by pavanpatil1** [comment]
Fixed and released in v2.2.3
