### ISSUE TITLE
Display Issue : Twenty Thirteen

### ISSUE THREAD

**Issue by sumeetsarna** [rtCamp/rtsocial#37]
rtSocial Placement Settings : Top

It is not exactly above post content

![not working exactly](https://cloud.githubusercontent.com/assets/8191145/5354051/afcde50c-7fa8-11e4-953c-eb7ca6ab7a7e.png)

**Comment by sanketio** [comment]
Ficed df4b30cc6b68b52af344720071b6413f6a504cbb
