### ISSUE TITLE
rtSocial (Linkedin Share Button)

### ISSUE THREAD

**Issue by NikhilJoshua** [rtCamp/rtsocial#69]
## Bug Report

**Current Behavior**
- Working fine on first plugin activation.
- After Dragging it to disable and re-dragging it to enable it *disappears*

**Expected behavior/code**
- After Re-Enabling it, the button should re-appear in the enable box 

**Steps to reproduce the bug**
- NA

**Testing Environment (if applicable)**
- ENV: WP-Local
- Browser: Google Chrome
- OS: Windows 10

**Possible Solution**

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.
![image](https://user-images.githubusercontent.com/8474784/132317279-8120ce5c-26c4-4fde-921b-1b26ee3490a0.png)

**Comment by aggarwaldev** [comment]
Unable to reproduce this issue with Foodmania theme.
@NikhilJoshua Can you please provide more details?

**Comment by NikhilJoshua** [comment]
I think it was a browser issue which made it disappear. Closing this issue as it's working fine now.
