### ISSUE TITLE
Need to fix PHPCS errors 

### ISSUE THREAD

**Issue by pooja-muchandikar** [rtCamp/rtsocial#76]
Reference:https://github.com/rtCamp/rtsocial/runs/4076266966?check_suite_focus=true

**Comment by Mukulsingh27** [comment]
Tested the complete plugin it's working fine and found no PHPCS errors in it.

**Comment by pooja-muchandikar** [comment]
@Mukulsingh27 

Can we get reference commit link where this issue is been fixed?

**Comment by Mukulsingh27** [comment]
@pooja-muchandikar 
I didn't find any reference commit link for this, what I did is run the PHPCS command:
`phpcs --standard=phpcs.xml . `
And found no errors.

**Comment by pavanpatil1** [comment]
The issue has been fixed. No errors are displayed after running the `phpcs --standard=phpcs.xml `   Hence closing this issue. 

![Screenshot from 2022-03-07 17-42-32](https://user-images.githubusercontent.com/44057535/157051816-9bb87e9a-08f4-4efe-bb76-596ab0a200f3.png)
