### ISSUE TITLE
Design issue observe on admin setting page

### ISSUE THREAD

**Issue by devanshijoshi9** [rtCamp/rtsocial#90]
## Bug Report

**Current Behavior**
- Added extra padding between the top and heading text.
- Header text size is small.

**Steps to reproduce**
- Go to admin rtsocial setting page

**Testing Environment**
- Tested in develop branch

**Additional context/Screenshots**

![Screenshot(20)](https://user-images.githubusercontent.com/86941664/156719373-70a7a1db-2a6b-4010-9836-921305c51f1e.png)

**Solution/After Screenshots**

![Screenshot(23)](https://user-images.githubusercontent.com/86941664/156743311-941bd6e4-086c-4a1c-869b-2a93317dc168.png)

**Comment by pavanpatil1** [comment]
```
Environment:
WordPress: v5.9.1
rtSocial: PR #94 
```
Cross-checked the issue. The fix is working fine. 


![image](https://user-images.githubusercontent.com/44057535/157179417-5de7d094-4469-4f10-9fc0-ec3f9ededdd3.png)

**Comment by pavanpatil1** [comment]
Fixed and released in v2.2.3
