### ISSUE TITLE
[ Admin ] Free support forums redirection link issue

### ISSUE THREAD

**Issue by devanshijoshi9** [rtCamp/rtsocial#94]
## Bug Report

**Current Behavior**
- Free support forums currently redirect to `https://community.rtcamp.com/category/rtsocial/` which gives error **`Did Not Connect: Potential Security Issue`** 

**Expected behavior/code**
- It should redirect to `https://wordpress.org/support/plugin/rtsocial/` instead of `https://community.rtcamp.com/category/rtsocial/`

**Testing Environment (if applicable)**

- Tested in Develop branch

**Possible Solution**
- Change href link with above mention link

**Additional Screenshots**

![Screenshot(24)](https://user-images.githubusercontent.com/86941664/156976285-6c1bba25-d961-4819-bacc-094fc5bbad0d.png)

**Comment by pavanpatil1** [comment]
```
Environment:
WordPress: v5.9.1
rtSocial: PR #94 
```
Cross-checked the issue. The fix is working fine.



https://user-images.githubusercontent.com/44057535/157191974-f47caeb5-55e2-46d7-bccf-2e8a53acfde6.mp4

**Comment by pavanpatil1** [comment]
Fixed and released in v2.2.3
