### ISSUE TITLE
On click on social icon the button text/image is not visible 

### ISSUE THREAD

**Issue by pavanpatil1** [rtCamp/rtsocial#97]
While sharing the post after clicking on the social media icon the button text is not visible. 

Expected result: Text/image should be visible. 

https://user-images.githubusercontent.com/44057535/157599202-babbc3ca-fb4e-4a9a-8f55-934ba91f070c.mp4

**Comment by Mukulsingh27** [comment]
Fixed in below PR 
1. #80

**Comment by pavanpatil1** [comment]
```
Environment:
WordPress: v5.9.1
rtSocial: develop
```

Cross-checked the issue. The fix is working fine.


Uploading Untitled_ Mar 11, 2022 9_51 AM.mp4…

**Comment by pavanpatil1** [comment]
Fixed and released in v2.2.3
